<?php

namespace MenuBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository {
    
    public function getTopSelling(): array {
        
        $categories = $this->createQueryBuilder("c")
            ->join("c.articles", "a")
            ->addSelect("a")
            ->where("c.route = '/category'");
        
        $articles = $categories->getQuery()->getResult();
        
        return $articles;
    }
    
    /**
     * Retourne les catégories de produit de niveau 1
     * @return array
     */
    public function getSliderImages(): array {
        $categoriesQuery = $this->createQueryBuilder("c")
            ->where("c.route = '/category'")
            ->andWhere("c.parent IS NULL");
        
        $categories = $categoriesQuery->getQuery()->getResult();
        
        return $categories;
    }
}
