<?php

namespace MenuBundle\Repository;

/**
 * MenuToCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuToCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
