<?php

namespace ContentBundle\Repository;

/**
 * DecorArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecorArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
