<?php

namespace UserBundle\Repository;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextOrderNum(): int {
        $query = $this->createQueryBuilder("b")
            ->select('COUNT(b.id) as quantity')
            ->from('UserBundle:Basket','order')
        ;
            
       $result = $query
        ->getQuery()
        ->getSingleScalarResult();
            
            
       return $result->quantity + 1;
    }
}